import Head from 'next/head'
import router, { useRouter } from 'next/router'
import { useEffect } from 'react'
import styles from '../../styles/Home.module.css'
import EnterQueueID from '../../views/EnterQueueID'

export default function JoinQueue() {

  // TODO: Allow slug to be used so that sharing is more elegant :)

  const router = useRouter();

  useEffect(() => {
    let userName = localStorage.getItem('QueuedUpUserName');
    let userId = localStorage.getItem('QueuedUpUserId');

    if (!userName || !userId) {
      router.push('/signin');
    };
  }, [router]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Join a Queue!</title>
        <meta name="Webservice for virtual queues" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <EnterQueueID />

    </div>
  )
}
