import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import QueueManager from '../../views/QueueManager';

export default function JoinQueue() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Queue Manager</title>
        <meta name="Webservice for virtual queues" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <QueueManager />

    </div>
  );
};
