import Head from 'next/head'
import FlexViewContainer from '../../components/FlexViewContainer';
import QueueManager from '../../views/QueueManager';

export default function JoinQueue() {
  return (
    <FlexViewContainer>
      <Head>
        <title>Queue Manager</title>
        <meta name="Webservice for virtual queues" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <QueueManager />

    </FlexViewContainer>
  );
};
