import Head from 'next/head'
import styles from '../styles/Home.module.css'
import WelcomeScreen from '../views/WelcomeScreen'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Queued Up</title>
        <meta name="Webservice for virtual queues" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WelcomeScreen />

    </div>
  )
}
