import Head from 'next/head'
import styles from '../styles/Home.module.css'
import EnterQueueID from '../views/EnterQueueID'
import WelcomeScreen from '../views/WelcomeScreen'

export default function JoinQueue() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Join a Queue!</title>
        <meta name="Webservice for virtual queues" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <EnterQueueID />

    </div>
  )
}
