import Head from "next/head";
import styles from '../styles/Home.module.css'
import CollectUserInfo from "../views/CollectUserInfo";

const SignIn = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Queued Up</title>
        <meta name="Webservice for virtual queues" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CollectUserInfo />

    </div>
  );
};

export default SignIn;
