import Head from "next/head";
import FlexViewContainer from "../components/FlexViewContainer";
import CollectUserInfo from "../views/CollectUserInfo";

const SignIn = () => {
  return (
    <FlexViewContainer>
      <Head>
        <title>Queued Up</title>
        <meta name="Webservice for virtual queues" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CollectUserInfo />

    </FlexViewContainer>
  );
};

export default SignIn;
