import { useRouter } from 'next/router'

import Head from 'next/head'
import QueueCreationConfirmation from '../../views/QueueCreationConfirmation';
import { useEffect, useState } from 'react';
import FlexViewContainer from '../../components/FlexViewContainer';

export default function ConfirmQueue() {

  const router = useRouter()

  const [stringQueueId, setStringQueueId] = useState(null); // stringQueueId is the string extracted from stringQueueId

  useEffect(() => {
    // test if Next router values are ready, and check that stringQueueId is not null
    if (router.isReady && (stringQueueId === null)) {
      // extract the slug from the url path
      const tempQueueId = router.query.queueId;

      if (typeof tempQueueId === 'string') {
        setStringQueueId(tempQueueId);
      }
      else if (Array.isArray(tempQueueId)) {
        // set stringQueueId to index 0 because the stringQueueId is the first entry in the slug per requirements
        setStringQueueId(tempQueueId[0]);
      }
      else {
        alert('NextJS url slug issue encountered :(')
      }
    }
  }, [router, stringQueueId])

  return (
    <FlexViewContainer>
      <Head>
        <title>Queue Position</title>
        <meta name="Webservice for virtual queues" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <QueueCreationConfirmation queueId={stringQueueId} />
    </FlexViewContainer>
  );
};
